# Generated by Django 3.2.19 on 2023-06-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='asdfs', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
